# Basic
title: KeJia Yin
subtitle: 
welcome_message: Welcome to my personal homepage
description: Now a 2022 MScAC student in University of Toronto                  Actively seeking Machine Learning Internships
creator: <a href="http://yinkejia.github.io">@KeJia Yin</a>

url: "https://github.com/yinkejia/yinkejia.github.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Home
    description: Visit Home

# Navigation buttons in the front page.
nav:
    - {title: ABOUT ME, description: My Projects, url: 'https://yinkejia.github.io/2021/08/ABOUT-ME/'}
    - {title: ACADEMIC, description: My Projects, url: 'https://yinkejia.github.io/2021/08/ACADEMIC-PERFORMANCE/'}
    - {title: RESEARCH, description: My Projects, url: 'https://yinkejia.github.io/2021/12/RESEARCH-EXPERIENCE/'}
    - {title: PROJECT, description: My Projects, url: 'https://yinkejia.github.io/2021/08/COURSE-PROJECT/'}
    - {title: SKILLS, description: My Projects, url: 'https://yinkejia.github.io/2021/12/AWARDS-&-LANGUAGES-&-SKILLS/'}
    
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"
    
# Social
social:
    #weibo: onevcat
    #github: onevcat
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: yinkejia@cs.toronto.edu


